server.port=8080
spring.application.name=api-gateway
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
jwt.secret=${JWT_SECRET:SisexpJwtSecret2026MicroservicesKey!}

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=usuarios
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.routes[2].id=techos
spring.cloud.gateway.routes[2].uri=lb://presupuesto-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/techos-presupuestales/**

spring.cloud.gateway.routes[3].id=poi
spring.cloud.gateway.routes[3].uri=lb://presupuesto-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/actividades-poi/**

spring.cloud.gateway.routes[4].id=pap
spring.cloud.gateway.routes[4].uri=lb://presupuesto-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/necesidades-pap/**

spring.cloud.gateway.routes[5].id=notas
spring.cloud.gateway.routes[5].uri=lb://presupuesto-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/notas-modificatorias/**

spring.cloud.gateway.routes[6].id=expedientes
spring.cloud.gateway.routes[6].uri=lb://expediente-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/expedientes/**

spring.cloud.gateway.routes[7].id=dashboard
spring.cloud.gateway.routes[7].uri=lb://auth-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/dashboard/**

spring.cloud.gateway.routes[8].id=reportes
spring.cloud.gateway.routes[8].uri=lb://expediente-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/reportes/**

spring.cloud.gateway.routes[9].id=notificaciones
spring.cloud.gateway.routes[9].uri=lb://notificacion-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.routes[10].id=health
spring.cloud.gateway.routes[10].uri=lb://auth-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/health

spring.cloud.gateway.routes[11].id=status
spring.cloud.gateway.routes[11].uri=lb://auth-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/status

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
